from __future__ import annotations
import torch
import torch.nn.functional as F
from ..geometry.se2 import wrap_angle_tensor

def periodic_yaw_loss(pred,target,yaw_enabled,yaw_valid):
    enabled=yaw_enabled.bool(); enabled=enabled[:,None].expand_as(pred) if enabled.ndim==1 else enabled; usable=enabled&yaw_valid.bool()
    if usable.any():
        d=wrap_angle_tensor(pred-target.to(pred.dtype)); return (1-torch.cos(d))[usable].mean()
    return pred.sum()*0.
def _warp(mask,disp,yaw,resolution):
    B,H,W=mask.shape; Fh=disp.shape[1]; canvas=F.pad(mask[:,None].to(disp.dtype),(W,W,H,H)); Hc,Wc=canvas.shape[-2:]; inp=canvas[:,None].expand(B,Fh,1,Hc,Wc).reshape(B*Fh,1,Hc,Wc); row=(torch.arange(Hc,device=inp.device,dtype=inp.dtype)-(Hc-1)/2)*resolution; col=(torch.arange(Wc,device=inp.device,dtype=inp.dtype)-(Wc-1)/2)*resolution; xo,yo=torch.meshgrid(row,col,indexing='ij'); xo=xo[None].expand(B*Fh,-1,-1)-disp.reshape(B*Fh,2)[:,0,None,None]; yo=yo[None].expand(B*Fh,-1,-1)-disp.reshape(B*Fh,2)[:,1,None,None]; th=yaw.reshape(B*Fh); c=torch.cos(th)[:,None,None]; s=torch.sin(th)[:,None,None]; xi=c*xo+s*yo; yi=-s*xo+c*yo; ri=xi/resolution+(Hc-1)/2; ci=yi/resolution+(Wc-1)/2; gy=2*ri/max(Hc-1,1)-1; gx=2*ci/max(Wc-1,1)-1; return F.grid_sample(inp,torch.stack((gx,gy),-1),mode='bilinear',padding_mode='zeros',align_corners=True).reshape(B,Fh,Hc,Wc)
def shape_overlap_loss(pred_disp,target_disp,pred_yaw,target_yaw,source_footprint,target_valid,yaw_enabled,yaw_label_valid,*,resolution=.8,eps=1e-6):
    B,Fh,_=pred_disp.shape; yu=yaw_enabled.bool()[:,None]&yaw_label_valid.bool(); py=torch.where(yu,pred_yaw,torch.zeros_like(pred_yaw)); ty=torch.where(yu,target_yaw.to(pred_yaw.dtype),torch.zeros_like(pred_yaw)); rel_yaw=wrap_angle_tensor(py-ty); delta=pred_disp-target_disp.to(pred_disp.dtype); cg=torch.cos(ty); sg=torch.sin(ty); rel=torch.stack((cg*delta[...,0]+sg*delta[...,1],-sg*delta[...,0]+cg*delta[...,1]),-1); warped=_warp(source_footprint,rel,rel_yaw,resolution); H,W=source_footprint.shape[-2:]; canonical=F.pad(source_footprint[:,None].to(warped.dtype),(W,W,H,H))[:,None].expand(B,Fh,1,3*H,3*W)[:,:,0]; inter=(warped*canonical).sum((-2,-1)); union=(warped+canonical-warped*canonical).sum((-2,-1)); iou=(inter+eps)/(union+eps); usable=target_valid.bool()&(source_footprint.flatten(1).sum(1)>0)[:,None]; return (1-iou[usable]).mean() if usable.any() else pred_disp.sum()*0.
def clean_objective(outputs,batch,*,yaw_weight=19.,shape_weight=.25,patch_resolution_m=.8):
    pred=outputs['residual_xy_m']; valid=batch['se2_target_valid'].bool(); tgt=batch['target_source_residual_xy_m'].to(pred.dtype); trans=F.smooth_l1_loss(pred[valid],tgt[valid],reduction='mean',beta=1.) if valid.any() else pred.sum()*0.; logits=outputs['existence_logits']; labels=batch['existence'].to(logits.dtype); exist=F.binary_cross_entropy_with_logits(logits,labels); yaw=periodic_yaw_loss(outputs['yaw_delta_rad'].float(),batch['target_yaw_rad'].float(),batch['yaw_enabled'],batch['yaw_label_valid']&valid); pred_disp=batch['kta_displacement_xy_m'].float()+pred.float(); shape=shape_overlap_loss(pred_disp,batch['target_source_displacement_xy_m'].float(),outputs['yaw_delta_rad'].float(),batch['target_yaw_rad'].float(),batch['target_source_mask_tube'][:,-1].float(),valid,batch['yaw_enabled'],batch['yaw_label_valid'],resolution=patch_resolution_m); total=trans+exist+yaw_weight*yaw+shape_weight*shape; return total,{'translation_smooth_l1':float(trans.detach()),'existence_bce':float(exist.detach()),'yaw_periodic_loss':float(yaw.detach()),'se2_shape_loss':float(shape.detach()),'objective_loss':float(total.detach())}
